#!/usr/bin/env node
// FlashDeck.AI — Vercel build script
// Generates config.js from environment variables at build time.
// The generated file is served as a static asset but never committed to Git.

const fs = require('fs');
const path = require('path');

const supabaseUrl  = process.env.SUPABASE_URL;
const supabaseAnon = process.env.SUPABASE_ANON;

if (!supabaseUrl || !supabaseAnon) {
  console.warn('[build.js] WARNING: SUPABASE_URL or SUPABASE_ANON not set.');
  console.warn('[build.js] Generating a placeholder config.js — auth will not work.');
}

const configContent = `// FlashDeck.AI — Runtime Configuration (auto-generated at build time)
// Do NOT edit this file manually. Set SUPABASE_URL and SUPABASE_ANON in Vercel.
window.FLASHDECK_CONFIG = {
  SUPABASE_URL:  '${supabaseUrl  || ''}',
  SUPABASE_ANON: '${supabaseAnon || ''}'
};
`;

const outputPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outputPath, configContent, 'utf8');
console.log('[build.js] config.js generated successfully.');
